import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/frontend/globals.css";
import { AppLayout } from "../components/appLayout/AppLayout";
import { UserProvider } from "../providers/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-200">
          <AppLayout>
            <UserProvider>
              {children}
            </UserProvider>
          </AppLayout>
        </div>
      </body>
    </html>
  );
}
